module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./index.html"],
  theme: {
    borderRadius: {
      none: "0px",
      sm: "3px",
      DEFAULT: "3px",
      md: "4px",
      lg: "4px",
      xl: "6px",
      "2xl": "8px",
      "3xl": "12px",
      full: "9999px",
    },
    extend: {
      fontFamily: {
        gothic: ['"MADE Okine Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        display: ['"MADE Okine Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ['"MADE Okine Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
      },
      colors: {
        void: "#171C1A",
        mint: "#9DECB8",
        bone: "#FBEFE3",
        ink: "#171C1A",
        ash: "rgba(23, 28, 26, 0.68)",
        jade: "#266A5A",
        leaf: "#66C072",
        blush: "#E693B3",
        "blush-soft": "#F3C1D2",
        "blush-deep": "#A83F72",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "#266A5A", foreground: "#9DECB8" },
        secondary: { DEFAULT: "#66C072", foreground: "#171C1A" },
        muted: { DEFAULT: "#66C072", foreground: "rgba(23, 28, 26, 0.68)" },
        accent: { DEFAULT: "#9DECB8", foreground: "#171C1A" },
        destructive: { DEFAULT: "#266A5A", foreground: "#9DECB8" },
        border: "rgba(23, 28, 26, 0.16)",
        input: "rgba(23, 28, 26, 0.18)",
        hairline: "rgba(23, 28, 26, 0.16)",
        ring: "#266A5A",
      },
      spacing: {
        "4.5": "18px",
        "13": "52px",
      },
      boxShadow: {
        soft: "0 10px 28px -12px rgba(0, 0, 0, 0.55)",
      },
      keyframes: {
        shimmer: { "0%": { backgroundPosition: "-200% 0" }, "100%": { backgroundPosition: "200% 0" } },
      },
      animation: {
        shimmer: "shimmer 1.8s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
};
