/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    borderRadius: {
      none: '0px',
      sm: '6px',
      DEFAULT: '6px',
      md: '6px',
      lg: '10px',
      xl: '10px',
      '2xl': '10px',
      '3xl': '16px',
      full: '9999px',
    },
    extend: {
      fontFamily: {
        display: ['"Inter"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['"Inter"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        'pixel-forest': '#2e7058',
        'pixel-teal': '#7fbcbf',
        'pixel-mint': '#a8e6cf',
        'pixel-pink': '#f7a1c4',
        'pixel-blush': '#ffdde6',
        'pixel-black': '#181411',
        'pixel-white': '#f7f4ef',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: '#2e7058', foreground: '#ffdde6' },
        secondary: { DEFAULT: '#ffdde6', foreground: '#2e7058' },
        muted: { DEFAULT: '#a8e6cf', foreground: '#2e7058' },
        accent: { DEFAULT: '#f7a1c4', foreground: '#181411' },
        destructive: { DEFAULT: '#c1272d', foreground: '#ffdde6' },
        border: '#7fbcbf',
        input: '#7fbcbf',
        ring: '#f7a1c4',
      },
      spacing: {
        '4.5': '18px',
        '13': '52px',
      },
      boxShadow: {
        'pixel-sm': '0 1px 2px 0 rgba(24, 20, 17, 0.06)',
        pixel: '0 6px 20px -6px rgba(24, 20, 17, 0.18)',
        'pixel-lg': '0 16px 40px -12px rgba(24, 20, 17, 0.22)',
        'pixel-pink': '0 6px 20px -6px rgba(24, 20, 17, 0.18)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-up': 'fade-up 0.6s ease-out both',
        shimmer: 'shimmer 1.8s ease-in-out infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
};
